services:
  giocci_relay:
    image: ghcr.io/biyooon-ex/giocci_platform/giocci_relay:${PROJECT_VERSION}
    build:
      context: ./
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      args:
        ELIXIR_VERSION: ${ELIXIR_VERSION}
        ERLANG_VERSION: ${ERLANG_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    volumes:
      - ./config/giocci_relay.exs:/app/giocci_relay.exs:ro
      - ./config/zenoh.json5:/app/zenoh.json5:ro
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
