name: publish2hex

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/biyooon-ex/giocci_platform/zenohd:1.8.0
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Prepare mix
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        run: mix deps.get

      - name: Publish to Hex.pm
        shell: bash
        run: |
          cd apps/giocci
          mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
